# Root ArgoCD Application - App of Apps Pattern
# IMPORTANT: Update repoURL to your actual Git repository before deploying
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vyrti/infra-hetzner-rancher-gitops.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
