# Alloy - Unified telemetry collector
# Scrapes metrics from cluster, collects logs, forwards traces
# Replaces Prometheus as the metrics scraper
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.5.1
    chart: alloy
    helm:
      values: |
        alloy:
          configMap:
            content: |
              // ============================================
              // KUBERNETES SERVICE DISCOVERY
              // ============================================
              
              discovery.kubernetes "nodes" {
                role = "node"
              }
              
              discovery.kubernetes "pods" {
                role = "pod"
              }
              
              discovery.kubernetes "services" {
                role = "service"
              }
              
              discovery.kubernetes "endpoints" {
                role = "endpoints"
              }
              
              // ============================================
              // POD RELABELING FOR LOGS
              // ============================================
              
              discovery.relabel "pods" {
                targets = discovery.kubernetes.pods.targets
                
                rule {
                  source_labels = ["__meta_kubernetes_namespace"]
                  target_label  = "namespace"
                }
                rule {
                  source_labels = ["__meta_kubernetes_pod_name"]
                  target_label  = "pod"
                }
                rule {
                  source_labels = ["__meta_kubernetes_pod_container_name"]
                  target_label  = "container"
                }
                rule {
                  source_labels = ["__meta_kubernetes_pod_node_name"]
                  target_label  = "node"
                }
                rule {
                  source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_name"]
                  separator     = "/"
                  target_label  = "job"
                }
              }
              
              // ============================================
              // LOG COLLECTION - KUBERNETES PODS
              // ============================================
              
              loki.source.kubernetes "pods" {
                targets    = discovery.relabel.pods.output
                forward_to = [loki.write.default.receiver]
              }
              
              loki.write "default" {
                endpoint {
                  url = "http://loki-gateway.monitoring.svc.cluster.local:80/loki/api/v1/push"
                }
              }
              
              // ============================================
              // METRICS SCRAPING - KUBE-STATE-METRICS
              // ============================================
              
              discovery.relabel "kube_state_metrics" {
                targets = discovery.kubernetes.services.targets
                
                rule {
                  source_labels = ["__meta_kubernetes_service_name"]
                  regex         = "kube-state-metrics"
                  action        = "keep"
                }
                rule {
                  source_labels = ["__meta_kubernetes_namespace"]
                  target_label  = "namespace"
                }
                rule {
                  replacement   = "kube-state-metrics"
                  target_label  = "job"
                }
              }
              
              prometheus.scrape "kube_state_metrics" {
                targets    = discovery.relabel.kube_state_metrics.output
                forward_to = [prometheus.remote_write.mimir.receiver]
                scrape_interval = "30s"
              }
              
              // ============================================
              // METRICS SCRAPING - ARGOCD
              // ============================================
              
              discovery.relabel "argocd" {
                targets = discovery.kubernetes.endpoints.targets
                
                rule {
                  source_labels = ["__meta_kubernetes_namespace"]
                  regex         = "argocd"
                  action        = "keep"
                }
                rule {
                  source_labels = ["__meta_kubernetes_endpoint_port_name"]
                  regex         = "metrics|http-exporter-port"
                  action        = "keep"
                }
                rule {
                  source_labels = ["__meta_kubernetes_service_name"]
                  target_label  = "job"
                }
              }
              
              prometheus.scrape "argocd" {
                targets    = discovery.relabel.argocd.output
                forward_to = [prometheus.remote_write.mimir.receiver]
                scrape_interval = "30s"
              }
              
              // ============================================
              // METRICS SCRAPING - NODE EXPORTER
              // ============================================
              
              discovery.relabel "node_exporter" {
                targets = discovery.kubernetes.endpoints.targets
                
                rule {
                  source_labels = ["__meta_kubernetes_endpoints_name"]
                  regex         = ".*node-exporter.*"
                  action        = "keep"
                }
                rule {
                  source_labels = ["__meta_kubernetes_endpoint_node_name"]
                  target_label  = "node"
                }
                rule {
                  replacement   = "node-exporter"
                  target_label  = "job"
                }
              }
              
              prometheus.scrape "node_exporter" {
                targets    = discovery.relabel.node_exporter.output
                forward_to = [prometheus.remote_write.mimir.receiver]
                scrape_interval = "30s"
              }
              
              // ============================================
              // METRICS SCRAPING - KUBELET/CADVISOR
              // ============================================
              
              discovery.relabel "kubelet" {
                targets = discovery.kubernetes.nodes.targets
                
                rule {
                  target_label = "__address__"
                  replacement  = "kubernetes.default.svc:443"
                }
                rule {
                  source_labels = ["__meta_kubernetes_node_name"]
                  regex         = "(.+)"
                  target_label  = "__metrics_path__"
                  replacement   = "/api/v1/nodes/$1/proxy/metrics"
                }
                rule {
                  source_labels = ["__meta_kubernetes_node_name"]
                  target_label  = "node"
                }
                rule {
                  replacement   = "kubelet"
                  target_label  = "job"
                }
              }
              
              prometheus.scrape "kubelet" {
                targets      = discovery.relabel.kubelet.output
                forward_to   = [prometheus.remote_write.mimir.receiver]
                scheme       = "https"
                bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
                tls_config {
                  ca_file              = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
                  insecure_skip_verify = true
                }
                scrape_interval = "30s"
              }
              
              discovery.relabel "cadvisor" {
                targets = discovery.kubernetes.nodes.targets
                
                rule {
                  target_label = "__address__"
                  replacement  = "kubernetes.default.svc:443"
                }
                rule {
                  source_labels = ["__meta_kubernetes_node_name"]
                  regex         = "(.+)"
                  target_label  = "__metrics_path__"
                  replacement   = "/api/v1/nodes/$1/proxy/metrics/cadvisor"
                }
                rule {
                  source_labels = ["__meta_kubernetes_node_name"]
                  target_label  = "node"
                }
                rule {
                  replacement   = "cadvisor"
                  target_label  = "job"
                }
              }
              
              prometheus.scrape "cadvisor" {
                targets      = discovery.relabel.cadvisor.output
                forward_to   = [prometheus.remote_write.mimir.receiver]
                scheme       = "https"
                bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
                tls_config {
                  ca_file              = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
                  insecure_skip_verify = true
                }
                scrape_interval = "30s"
              }
              
              // ============================================
              // REMOTE WRITE TO MIMIR
              // ============================================
              
              prometheus.remote_write "mimir" {
                endpoint {
                  url = "http://mimir-gateway.mimir.svc.cluster.local:80/api/v1/push"
                }
              }
              
              // ============================================
              // OTLP RECEIVER FOR TRACES
              // ============================================
              
              otelcol.receiver.otlp "default" {
                grpc {
                  endpoint = "0.0.0.0:4317"
                }
                http {
                  endpoint = "0.0.0.0:4318"
                }
                output {
                  traces = [otelcol.exporter.otlp.tempo.input]
                }
              }
              
              otelcol.exporter.otlp "tempo" {
                client {
                  endpoint = "tempo.monitoring.svc.cluster.local:4317"
                  tls {
                    insecure = true
                  }
                }
              }
        
        controller:
          type: daemonset
        
        # RBAC for cluster-wide access
        serviceAccount:
          create: true
        
        rbac:
          create: true
        
        # Tolerate all taints to run on all nodes
        tolerations:
          - operator: Exists
        
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
