# ClusterIssuer Application - Deploys Let's Encrypt issuer
# IMPORTANT: Update repoURL to your actual Git repository
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Deploy before other apps
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/hetzner-rancher.git  # <-- UPDATE THIS
    targetRevision: HEAD
    path: gitops/bootstrap
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true