# Grafana - Observability dashboard
# Pre-configured with Mimir, Loki, Tempo datasources
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 10.3.2
    chart: grafana
    helm:
      values: |
        adminUser: admin
        adminPassword: admin  # Change in production!
        
        deploymentStrategy:
          type: Recreate
        
        ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
          hosts:
            - grafana.aleklab.com
          tls:
            - secretName: grafana-tls
              hosts:
                - grafana.aleklab.com
        
        persistence:
          enabled: true
          size: 1Gi
        
        # Pre-configured datasources
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Mimir
                type: prometheus
                url: http://mimir-gateway.mimir.svc.cluster.local:80/prometheus
                access: proxy
                isDefault: true  # Mimir is primary metrics source
              - name: Loki
                type: loki
                url: http://loki-gateway.monitoring.svc.cluster.local:80
                access: proxy
                jsonData:
                  derivedFields:
                    - datasourceUid: tempo
                      matcherRegex: "trace_id=(\\w+)"
                      name: TraceID
                      url: "$${__value.raw}"
              - name: Tempo
                type: tempo
                uid: tempo
                url: http://tempo.monitoring.svc.cluster.local:3100
                access: proxy
                jsonData:
                  tracesToLogs:
                    datasourceUid: loki
                    tags: ['job', 'namespace', 'pod']
        
        # Dashboard providers
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: 'default'
                orgId: 1
                folder: ''
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default
        
        # Sidecar for configmap dashboards
        sidecar:
          dashboards:
            enabled: true
            searchNamespace: ALL
          datasources:
            enabled: true
            searchNamespace: ALL
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
