# KEDA - Kubernetes Event-driven Autoscaling
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.18.2
    chart: keda
    helm:
      values: |
        operator:
          replicaCount: 1
        metricsServer:
          replicaCount: 1
        webhooks:
          replicaCount: 1
        resources:
          operator:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          metricServer:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
        prometheus:
          metricServer:
            enabled: true
          operator:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
