# Mimir - Long-term metrics storage
# Receives metrics from Prometheus via remote write
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Deploy before Prometheus
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.0.5
    chart: mimir-distributed
    helm:
      values: |
        # Minimal deployment for small clusters
        kafka:
          persistence:
            size: 1Gi
          image:
            tag: 3.6.1-debian-11-r0
        etcd:
          persistence:
            size: 1Gi
        mimir:
          auth_enabled: false
          structuredConfig:
            common:
              storage:
                backend: s3
                s3:
                  endpoint: mimir-minio.mimir.svc:9000
                  access_key_id: grafana-mimir
                  secret_access_key: supersecret
                  insecure: true
                  bucket_name: mimir-tsdb
            blocks_storage:
              backend: s3
              s3:
                endpoint: mimir-minio.mimir.svc:9000
                access_key_id: grafana-mimir
                secret_access_key: supersecret
                insecure: true
                bucket_name: mimir-tsdb

            ruler_storage:
              backend: s3
              s3:
                bucket_name: mimir-ruler
            limits:
              max_global_series_per_user: 1500000
              max_global_series_per_metric: 50000
              ingestion_rate: 50000
              ingestion_burst_size: 100000
            compactor:
              data_dir: /data/compactor
            ingester:
              ring:
                replication_factor: 1
            store_gateway:
              sharding_ring:
                replication_factor: 1
        
        # Deployment components
        alertmanager:
          enabled: false
        
        compactor:
          replicas: 1
          persistentVolume:
            enabled: true
            size: 3Gi
        
        distributor:
          replicas: 1
        
        ingester:
          replicas: 1
          persistentVolume:
            enabled: true
            size: 3Gi
          zoneAwareReplication:
            enabled: false
        
        overrides_exporter:
          enabled: false
        
        querier:
          replicas: 1
        
        query_frontend:
          replicas: 1
        
        query_scheduler:
          enabled: true
        
        ruler:
          enabled: false
        
        store_gateway:
          replicas: 1
          persistentVolume:
            enabled: true
            size: 3Gi
          zoneAwareReplication:
            enabled: false
        
        # Nginx gateway
        nginx:
          enabled: true
          replicas: 1
          nginxConfig:
            resolver: rke2-coredns-rke2-coredns.kube-system.svc.cluster.local
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
            hosts:
              - host: mimir.aleklab.com
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: mimir-tls
                hosts:
                  - mimir.aleklab.com
        
        # Enable minio for storage
        minio:
          enabled: true
          persistence:
            size: 3Gi
        
        rollout_operator:
          enabled: false
        
        # Disable monitoring (no prometheus-operator CRDs)
        metaMonitoring:
          serviceMonitor:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: mimir
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
