# MLflow - Machine Learning Lifecycle Platform
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    targetRevision: 1.8.1 # Using confirmed version from search
    chart: mlflow
    helm:
      values: |
        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: mlflow.aleklab.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: mlflow-tls
              hosts:
                - mlflow.aleklab.com

        # Artifact Storage (S3)
        # Using existing Velero MinIO instance
        artifactRoot:
          s3:
            enabled: true
            bucket: mlflow
            awsAccessKeyId: minio
            awsSecretAccessKey: minio123

        # Environment variables to point to Velero MinIO
        extraEnvVars:
          MLFLOW_S3_ENDPOINT_URL: http://velero-minio.velero.svc:9000
          MLFLOW_S3_IGNORE_TLS: "true"

        # Backend Storage (PostgreSQL)
        backendStore:
          postgres:
            enabled: true
            host: mlflow-postgresql
            port: 5432
            database: mlflow
            user: mlflow
            password: mlflow123

        # Disable internal MinIO (using Velero's)
        minio:
          enabled: false

        # Enable PostgreSQL subchart
        postgresql:
          enabled: true
          global:
            postgresql:
              auth:
                username: mlflow
                password: mlflow123
                database: mlflow

  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
