# Node Exporter - Host/node metrics
# Provides hardware and OS metrics from each node
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 4.49.2
    chart: prometheus-node-exporter
    helm:
      values: |
        # Run as DaemonSet on all nodes
        hostNetwork: true
        hostPID: true
        hostRootFsMount:
          enabled: true
        
        # Tolerate all taints to run on all nodes
        tolerations:
          - operator: Exists
        
        # Resource limits
        resources:
          requests:
            cpu: 50m
            memory: 30Mi
          limits:
            cpu: 200m
            memory: 50Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
