apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sysctl-tuner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/vyrti/infra-hetzner-rancher-gitops.git
    targetRevision: HEAD
    path: apps/sysctl-tuner-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
