# Tempo - Distributed tracing backend
# Single binary mode for cluster tracing
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.24.1
    chart: tempo
    helm:
      values: |
        tempo:
          storage:
            trace:
              backend: local
              local:
                path: /var/tempo/traces
              wal:
                path: /var/tempo/wal
          
          # Receivers for trace ingestion
          receivers:
            jaeger:
              protocols:
                thrift_compact:
                  endpoint: "0.0.0.0:6831"
                thrift_http:
                  endpoint: "0.0.0.0:14268"
                grpc:
                  endpoint: "0.0.0.0:14250"
            zipkin:
              endpoint: "0.0.0.0:9411"
            otlp:
              protocols:
                grpc:
                  endpoint: "0.0.0.0:4317"
                http:
                  endpoint: "0.0.0.0:4318"
        
        persistence:
          enabled: true
          size: 20Gi
        
        # Enable service monitor
        serviceMonitor:
          enabled: true
        
        # Resource limits
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
