# Velero - Kubernetes Backup and Disaster Recovery
# Uses Helm chart 11.2.0 with Velero v1.17.1
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 11.2.0
    chart: velero
    helm:
      values: |
        ## Configuration settings that directly affect the Velero deployment YAML.
        image:
          repository: velero/velero
          tag: v1.17.1

        # Init containers to add to the Velero deployment's pod spec.
        # AWS plugin is required for S3-compatible (MinIO) storage.
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.13.1
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins

        # Velero configuration
        configuration:
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: velero-backups
              config:
                region: minio
                s3ForcePathStyle: "true"
                s3Url: http://velero-minio:9000
          volumeSnapshotLocation:
            - name: default
              provider: aws
              config:
                region: minio
          # Default backup TTL (30 days)
          defaultBackupTTL: 720h
          # Enable CSI snapshots
          features: EnableCSI
          # Use Kopia for filesystem backups (v1.14+ default)
          uploaderType: kopia

        # Credentials for MinIO
        credentials:
          useSecret: true
          name: velero-credentials
          secretContents:
            cloud: |
              [default]
              aws_access_key_id = minio
              aws_secret_access_key = minio123

        # Set true for backup all pod volumes without having to apply annotation
        defaultVolumesToFsBackup: true

        # Whether to deploy the node-agent daemonset (replaces restic in newer versions)
        deployNodeAgent: true

        # Schedule default backups
        schedules:
          daily-backup:
            disabled: false
            schedule: "0 3 * * *"  # Daily at 3 AM
            template:
              ttl: 168h  # 7 days retention
              includedNamespaces:
                - gitlab
                - openbao
                - monitoring
                - kubecost
              storageLocation: default
          weekly-full-backup:
            disabled: false
            schedule: "0 4 * * 0"  # Sunday at 4 AM
            template:
              ttl: 720h  # 30 days retention
              includedNamespaces:
                - "*"
              excludedNamespaces:
                - kube-system
                - kube-public
              storageLocation: default

        # Resource limits for Velero server
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi

        # Node agent (for filesystem backups)
        nodeAgent:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi

        # Prometheus metrics
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true

        # Extra objects to deploy a small MinIO for Velero storage
        extraObjects:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: velero-minio
              namespace: velero
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: minio
              template:
                metadata:
                  labels:
                    app: minio
                spec:
                  containers:
                  - name: minio
                    image: minio/minio:latest
                    args:
                    - server
                    - /data
                    - --console-address
                    - :9001
                    env:
                    - name: MINIO_ROOT_USER
                      value: minio
                    - name: MINIO_ROOT_PASSWORD
                      value: minio123
                    ports:
                    - containerPort: 9000
                    - containerPort: 9001
                    volumeMounts:
                    - name: storage
                      mountPath: /data
                  volumes:
                  - name: storage
                    persistentVolumeClaim:
                      claimName: velero-minio-pvc
          - apiVersion: v1
            kind: Service
            metadata:
              name: velero-minio
              namespace: velero
            spec:
              type: ClusterIP
              ports:
                - port: 9000
                  targetPort: 9000
                  name: api
                - port: 9001
                  targetPort: 9001
                  name: console
              selector:
                app: minio
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: velero-minio-pvc
              namespace: velero
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 3Gi
          - apiVersion: batch/v1
            kind: Job
            metadata:
              name: velero-minio-init
              namespace: velero
            spec:
              template:
                spec:
                  containers:
                  - name: mc
                    image: minio/mc:latest
                    command:
                    - /bin/sh
                    - -c
                    - |
                      until (mc alias set minio http://velero-minio:9000 minio minio123); do echo 'waiting for minio...'; sleep 1; done;
                      mc mb --ignore-existing minio/velero-backups;
                      exit 0;
                  restartPolicy: OnFailure

  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
